allowBuilds:
  msgpackr-extract: true
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  "postcss": ">=8.5.10"
  "undici": "7.28.0"
minimumReleaseAge: 10080
trustPolicy:
  no-downgrade: true
