allowBuilds:
  msgpackr-extract: true
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  "postcss": ">=8.5.10"
  tmp: ^0.2.4
minimumReleaseAge: 10080
